services:
  fastapi:
    image: docker.pkg.github.com/polisthefano/valuewineback/microservicio:dev
    build: .
    replicas: 1
    ports:
      - 8080:8080
    resources:
      cpu: 100m
      memory: 128Mi